ASFLAGS_ADDITIONAL = "@$(ARDUINO_MBED_ROOT)/hardware/mbed/$(MBED_LIB_VERSION)/variants/ARDUINO_NANO33BLE/defines.txt" "@$(ARDUINO_MBED_ROOT)/hardware/mbed/$(MBED_LIB_VERSION)/variants/ARDUINO_NANO33BLE/cxxflags.txt"  -DARDUINO_ARCH_NRF52840 -DARDUINO=10819 -DARDUINO_ARDUINO_NANO33BLE -DARDUINO_ARCH_MBED "-I$(ARDUINO_MBED_ROOT)/hardware/mbed/$(MBED_LIB_VERSION)/cores/arduino" "-I$(ARDUINO_MBED_ROOT)/hardware/mbed/$(MBED_LIB_VERSION)/variants/ARDUINO_NANO33BLE" "-I$(ARDUINO_MBED_ROOT)/hardware/mbed/$(MBED_LIB_VERSION)/cores/arduino/api/deprecated"  "-iprefix$(ARDUINO_MBED_ROOT)/hardware/mbed/$(MBED_LIB_VERSION)/cores/arduino" "@$(ARDUINO_TARGET_ROOT)/include/MW_arduinoBLESense_Incl.txt"
TARGET_LOAD_CMD = 
TARGET_LOAD_CMD_ARGS = 
TARGET_PKG_INSTALLDIR = C:/PROGRA~3/MATLAB/SUPPOR~1/R2021b/toolbox/target/SUPPOR~1/ARDUIN~1/registry/..
STACK_SIZE = 64
