#ifndef PORTABLE_WORDSIZES
#ifdef __MW_TARGET_USE_HARDWARE_RESOURCES_H__
#ifndef __MW_TARGET_HARDWARE_RESOURCES_H__
#define __MW_TARGET_HARDWARE_RESOURCES_H__

#define MW_MULTI_TASKING_MODE 1
#include "main.h"
#include "SysTickScheduler.h"
#include "arm_cortex_m_multitasking.h"

#define MW_USECODERTARGET 1
#define MW_TARGETHARDWARE STM32F4xx Based
#define MW_CONNECTIONINFO_SERIAL_BAUDRATE stm32cube.codegen.getConnectivityBaudrate(hCS)
#define MW_CONNECTIONINFO_SERIAL_COMPORT stm32cube.codegen.getConnectivityCOMPort(hCS)
#define MW_CONNECTIONINFO_SERIAL_VERBOSE 1
#define MW_EXTMODE_CONFIGURATION serial
#define MW_EXTMODE_SIGNALBUFFERSIZE 2048.000000
#define MW_EXTMODE_USEREALTIMESTAMPLOGGING 1
#define MW_RTOS Baremetal
#define MW_SCHEDULER_INTERRUPT_SOURCE 0
#define MW_RUNTIME_BUILDACTION 1
#define MW_STM32CUBEMX_PROJECTFILEBUTTON 
#define MW_STM32CUBEMX_CREATEPROJECTFILEBUTTON 
#define MW_STM32CUBEMX_LAUNCHPROJECTFILEBUTTON 
#define MW_STM32CUBEMX_PROJECTFILE C:/Users/eahil/Documents/GitHub/smart-cpr-algo/src/cpr-algo/top_level_algo/top_level_algo.ioc
#define MW_STM32CUBEMX_DEVICEID STM32F429ZITx
#define MW_STM32CUBEMX_FAMILY STM32F4
#define MW_STM32CUBEMX_CONNECTIVITYMODE 0
#define MW_STM32CUBEMX_AUTODETECTBOARD 1
#define MW_STM32CUBEMX_DEVICELIST -1
#define MW_STM32CUBEMX_DEVICELISTREFRESH 
#define MW_CLOCKING_CPUCLOCKRATEMHZ 168.000000
#define MW_CONNECTION_SERIALMODULE 0
#define MW_CONNECTION_SERIALPORT COM10
#define MW_ADC1_USEDMA 0
#define MW_ADC1_USEWATCHDOG 0
#define MW_ADC1_EOCENABLEINTERRUPT 0
#define MW_ADC1_JEOCENABLEINTERRUPT 48
#define MW_ADC1_OVRENABLEINTERRUPT 48
#define MW_ADC1_PROJECTFILEBUTTON 
#define MW_ADC2_USEDMA 0
#define MW_ADC2_USEWATCHDOG 0
#define MW_ADC2_EOCENABLEINTERRUPT 0
#define MW_ADC2_JEOCENABLEINTERRUPT 48
#define MW_ADC2_OVRENABLEINTERRUPT 48
#define MW_ADC2_PROJECTFILEBUTTON 
#define MW_ADC3_USEDMA 1
#define MW_ADC3_USEWATCHDOG 0
#define MW_ADC3_EOCENABLEINTERRUPT 1
#define MW_ADC3_JEOCENABLEINTERRUPT 48
#define MW_ADC3_OVRENABLEINTERRUPT 48
#define MW_ADC3_PROJECTFILEBUTTON 
#define MW_TIM1_TRIGGERINTERRUPT 48
#define MW_TIM1_CAPTURECOMPARE1INTERRUPT 48
#define MW_TIM1_CAPTURECOMPARE2INTERRUPT 48
#define MW_TIM1_CAPTURECOMPARE3INTERRUPT 48
#define MW_TIM1_CAPTURECOMPARE4INTERRUPT 48
#define MW_TIM1_UPDATEINTERRUPT 48
#define MW_TIM1_BREAKINTERRUPT 48
#define MW_TIM2_TRIGGERINTERRUPT 48
#define MW_TIM2_CAPTURECOMPARE1INTERRUPT 48
#define MW_TIM2_CAPTURECOMPARE2INTERRUPT 48
#define MW_TIM2_CAPTURECOMPARE3INTERRUPT 48
#define MW_TIM2_CAPTURECOMPARE4INTERRUPT 48
#define MW_TIM2_UPDATEINTERRUPT 48
#define MW_TIM3_TRIGGERINTERRUPT 48
#define MW_TIM3_CAPTURECOMPARE1INTERRUPT 48
#define MW_TIM3_CAPTURECOMPARE2INTERRUPT 48
#define MW_TIM3_CAPTURECOMPARE3INTERRUPT 48
#define MW_TIM3_CAPTURECOMPARE4INTERRUPT 48
#define MW_TIM3_UPDATEINTERRUPT 48
#define MW_TIM4_TRIGGERINTERRUPT 48
#define MW_TIM4_CAPTURECOMPARE1INTERRUPT 48
#define MW_TIM4_CAPTURECOMPARE2INTERRUPT 48
#define MW_TIM4_CAPTURECOMPARE3INTERRUPT 48
#define MW_TIM4_CAPTURECOMPARE4INTERRUPT 48
#define MW_TIM4_UPDATEINTERRUPT 48
#define MW_TIM5_TRIGGERINTERRUPT 48
#define MW_TIM5_CAPTURECOMPARE1INTERRUPT 48
#define MW_TIM5_CAPTURECOMPARE2INTERRUPT 48
#define MW_TIM5_CAPTURECOMPARE3INTERRUPT 48
#define MW_TIM5_CAPTURECOMPARE4INTERRUPT 48
#define MW_TIM5_UPDATEINTERRUPT 48
#define MW_TIM8_TRIGGERINTERRUPT 48
#define MW_TIM8_CAPTURECOMPARE1INTERRUPT 48
#define MW_TIM8_CAPTURECOMPARE2INTERRUPT 48
#define MW_TIM8_CAPTURECOMPARE3INTERRUPT 48
#define MW_TIM8_CAPTURECOMPARE4INTERRUPT 48
#define MW_TIM8_UPDATEINTERRUPT 48
#define MW_TIM8_BREAKINTERRUPT 48
#define MW_TIM9_TRIGGERINTERRUPT 48
#define MW_TIM9_CAPTURECOMPARE1INTERRUPT 48
#define MW_TIM9_CAPTURECOMPARE2INTERRUPT 48
#define MW_TIM9_UPDATEINTERRUPT 48
#define MW_TIM10_CAPTURECOMPARE1INTERRUPT 48
#define MW_TIM10_UPDATEINTERRUPT 48
#define MW_TIM11_CAPTURECOMPARE1INTERRUPT 48
#define MW_TIM11_UPDATEINTERRUPT 48
#define MW_TIM12_TRIGGERINTERRUPT 48
#define MW_TIM12_CAPTURECOMPARE1INTERRUPT 48
#define MW_TIM12_CAPTURECOMPARE2INTERRUPT 48
#define MW_TIM12_UPDATEINTERRUPT 48
#define MW_TIM13_CAPTURECOMPARE1INTERRUPT 48
#define MW_TIM13_UPDATEINTERRUPT 48
#define MW_TIM14_CAPTURECOMPARE1INTERRUPT 48
#define MW_TIM14_UPDATEINTERRUPT 48
#define MW_DATAVERSION 2016.02
#define MW_STM32_ANALOGINPUT_ID 841
#define MW_STM32_DIGITALPORTWRITE_ID 867

#endif /* __MW_TARGET_HARDWARE_RESOURCES_H__ */

#endif

#endif
